-- Add all GE course departments and courses
-- This migration adds SJSU General Education courses to support transcript import

-- First, add all departments
INSERT INTO public.departments (code, name) VALUES
  ('POLS', 'Political Science'),
  ('NAIS', 'Native American Indigenous Studies'),
  ('ENGL', 'English'),
  ('ANTH', 'Anthropology'),
  ('COMM', 'Communication Studies'),
  ('ENVS', 'Environmental Studies'),
  ('HIST', 'History'),
  ('HUM', 'Humanities'),
  ('LING', 'Linguistics'),
  ('NUFS', 'Nutrition and Food Science'),
  ('PHIL', 'Philosophy'),
  ('CCS', 'Chicanx and Chicano Studies'),
  ('CHAD', 'Child and Adolescent Development'),
  ('ESM', 'Elementary STEM Education'),
  ('JS', 'Justice Studies'),
  ('MATH', 'Mathematics'),
  ('PH', 'Public Health'),
  ('SOCI', 'Sociology'),
  ('SOCS', 'Social Sciences'),
  ('STAT', 'Statistics'),
  ('UNVS', 'University'),
  ('AMS', 'American Studies'),
  ('ARTH', 'Art History'),
  ('ASIA', 'Asian Studies'),
  ('CA', 'Creative Arts'),
  ('DANC', 'Dance'),
  ('FORL', 'Foreign Languages'),
  ('KIN', 'Kinesiology'),
  ('MUSC', 'Music'),
  ('RTVF', 'Radio Television Film'),
  ('TA', 'Theatre Arts'),
  ('CHIN', 'Chinese'),
  ('FREN', 'French'),
  ('GERM', 'German'),
  ('HEBR', 'Hebrew'),
  ('ITAL', 'Italian'),
  ('JPN', 'Japanese'),
  ('JWSS', 'Jewish Studies'),
  ('LSTP', 'Learning, Science, and Technology Program'),
  ('MDES', 'Middle Eastern Studies'),
  ('PORT', 'Portuguese'),
  ('RELS', 'Religious Studies'),
  ('RUSS', 'Russian'),
  ('SPAN', 'Spanish'),
  ('TAG', 'Tagalog'),
  ('VIET', 'Vietnamese'),
  ('AAS', 'Asian American Studies'),
  ('AFAM', 'African American Studies'),
  ('ECON', 'Economics'),
  ('ENGR', 'Engineering'),
  ('GEOG', 'Geography'),
  ('GERO', 'Gerontology'),
  ('JOUR', 'Journalism'),
  ('PSYC', 'Psychology'),
  ('WGSS', 'Women Gender and Sexuality Studies'),
  ('ASTR', 'Astronomy'),
  ('CHE', 'Chemical Engineering'),
  ('CHEM', 'Chemistry'),
  ('GEOL', 'Geology'),
  ('METR', 'Meteorology'),
  ('PHYS', 'Physics'),
  ('SCED', 'Science Education'),
  ('BIOL', 'Biology'),
  ('GLST', 'Global Studies'),
  ('MICR', 'Microbiology')
ON CONFLICT (code) DO NOTHING;

-- Now add all GE courses
-- Area 1A: Written Communication
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('ENGL', '1A', 'First Year Writing', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '1AS', 'First-Year Writing: Stretch English II', 3, (SELECT id FROM public.departments WHERE code = 'ENGL'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 1B: Critical Thinking and Writing
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('ANTH', '13', 'Archaeology', 3, (SELECT id FROM public.departments WHERE code = 'ANTH')),
  ('COMM', '41', 'Critical Decision Making', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('COMM', '45', 'Media and Culture', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('COMM', '74', 'Intercultural Communication and Critical Thinking', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('ENGL', '2', 'Critical Thinking and Writing', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENVS', '1', 'Introduction to Environmental Issues', 3, (SELECT id FROM public.departments WHERE code = 'ENVS')),
  ('HIST', '50', 'Historical Process: Understanding Historical Reasoning', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HUM', '11', 'Honors Critical Thinking across Global Cultures', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('HUM', '80', 'Reading the World', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('LING', '21', 'Critical Thinking and Language', 3, (SELECT id FROM public.departments WHERE code = 'LING')),
  ('LING', '24', 'Language Variation in Space, Time, & Culture', 3, (SELECT id FROM public.departments WHERE code = 'LING')),
  ('NUFS', '40', 'Debunking Nutrition Misinformation', 3, (SELECT id FROM public.departments WHERE code = 'NUFS')),
  ('PHIL', '57', 'Logic and Critical Reasoning', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('POLS', '20', 'Controversial Legal Issues', 3, (SELECT id FROM public.departments WHERE code = 'POLS'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 1C: Oral Communication
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('CCS', '74', 'Public Address', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('COMM', '20', 'Public Speaking', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('COMM', '20EL', 'Public Speaking for English Language Learners', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('COMM', '40', 'Argumentation and Advocacy', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('HUM', '10', 'Honors Global Oral and Rhetorical Cultures', 3, (SELECT id FROM public.departments WHERE code = 'HUM'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 2: Mathematics and Quantitative Reasoning
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('CHAD', '80', 'Quantitative Analysis in Developmental Science', 3, (SELECT id FROM public.departments WHERE code = 'CHAD')),
  ('CS', '22A', 'Python for Everyone', 3, (SELECT id FROM public.departments WHERE code = 'CS')),
  ('ESM', '1', 'Mathematical Reasoning', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '9', 'Mathematics and Logic for General Education', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '10A', 'Mathematics in Art and Music', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '10D', 'Probability, Data Science, Ethics, and You', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '10P', 'Mathematics in Politics', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '15', 'Statway: Statistics-Concepts & Methods', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '18A', 'College Algebra', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '19', 'Precalculus', 5, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('ESM', '26', 'Quantitative Reasoning in Linguistic Diversity', 3, (SELECT id FROM public.departments WHERE code = 'ESM')),
  ('JS', '15', 'Introductory Statistics in Justice Studies', 3, (SELECT id FROM public.departments WHERE code = 'JS')),
  ('LING', '26', 'Quantitative Reasoning in Linguistic Diversity', 3, (SELECT id FROM public.departments WHERE code = 'LING')),
  ('MATH', '10', 'Mathematics for General Education', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '10A', 'Mathematics in Art and Music', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '10D', 'Probability, Data Science, Ethics, and You', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '10P', 'Mathematics in Politics', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '12', 'Number Systems', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '15', 'Statway: Statistics-Concepts & Methods', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '18A', 'College Algebra', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '19', 'Precalculus', 5, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '30', 'Calculus I', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '31', 'Calculus II', 4, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '32', 'Calculus III', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '70', 'Mathematics for Business', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('MATH', '71', 'Calculus for Business and Aviation', 3, (SELECT id FROM public.departments WHERE code = 'MATH')),
  ('NUFS', '41', 'Quantitative Reasoning in Human Nutrition', 3, (SELECT id FROM public.departments WHERE code = 'NUFS')),
  ('PH', '67', 'Introductory Health Statistics', 3, (SELECT id FROM public.departments WHERE code = 'PH')),
  ('PHIL', '9', 'Mathematics and Logic for General Education', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('SOCI', '15', 'Statistical Applications in the Social Sciences', 3, (SELECT id FROM public.departments WHERE code = 'SOCI')),
  ('SOCS', '15', 'Statistical Applications in the Social Sciences', 3, (SELECT id FROM public.departments WHERE code = 'SOCS')),
  ('STAT', '95', 'Elementary Statistics', 3, (SELECT id FROM public.departments WHERE code = 'STAT')),
  ('UNVS', '15', 'Statway: Statistics-Concepts & Methods', 3, (SELECT id FROM public.departments WHERE code = 'UNVS'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 3A: Arts
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('AMS', '12', 'Intro to US Popular Culture: Serious Fun!', 3, (SELECT id FROM public.departments WHERE code = 'AMS')),
  ('ARTH', '15', 'Intro to Visual Culture', 3, (SELECT id FROM public.departments WHERE code = 'ARTH')),
  ('ARTH', '70A', 'Art History, Prehistoric to Medieval', 3, (SELECT id FROM public.departments WHERE code = 'ARTH')),
  ('ARTH', '70B', 'Art History, Renaissance to Modern', 3, (SELECT id FROM public.departments WHERE code = 'ARTH')),
  ('ARTH', '70C', 'Arts of Asia', 3, (SELECT id FROM public.departments WHERE code = 'ARTH')),
  ('ARTH', '72', 'Design in Society', 3, (SELECT id FROM public.departments WHERE code = 'ARTH')),
  ('ASIA', '19', 'Music in World Cultures', 3, (SELECT id FROM public.departments WHERE code = 'ASIA')),
  ('ASIA', '30', 'From Chinese Traditions to Multicultural Paradigms: Martial Arts Films around the World', 3, (SELECT id FROM public.departments WHERE code = 'ASIA')),
  ('ASIA', '70C', 'Arts of Asia', 3, (SELECT id FROM public.departments WHERE code = 'ASIA')),
  ('CA', '95', 'Introduction to Queer Arts', 3, (SELECT id FROM public.departments WHERE code = 'CA')),
  ('DANC', '10', 'Dance Appreciation', 3, (SELECT id FROM public.departments WHERE code = 'DANC')),
  ('ENGL', '71', 'Creative Writing', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('FORL', '30', 'From Chinese Traditions to Multicultural Paradigms: Martial Arts Films around the World', 3, (SELECT id FROM public.departments WHERE code = 'FORL')),
  ('HUM', '20', 'Honors Global Material Cultures', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('KIN', '68', 'Visual Representations of Sport in Popular Culture', 3, (SELECT id FROM public.departments WHERE code = 'KIN')),
  ('MUSC', '4A', 'Music Theory 4A', 2, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '4B', 'Musicianship 4B', 1, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '10A', 'Music Appreciation', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '10B', 'Introduction to Music', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '10C', 'Pop and Rock in the U.S.', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '10D', 'Introduction to Hip Hop', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('MUSC', '19', 'Music in World Cultures', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('PHIL', '66', 'Introduction to Aesthetics', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('RTVF', '10', 'The Art of Film', 3, (SELECT id FROM public.departments WHERE code = 'RTVF')),
  ('TA', '5', 'Beginning Acting', 3, (SELECT id FROM public.departments WHERE code = 'TA')),
  ('TA', '10', 'Theatre Appreciation', 3, (SELECT id FROM public.departments WHERE code = 'TA')),
  ('TA', '55', 'Intro to Design for the Performing Arts', 3, (SELECT id FROM public.departments WHERE code = 'TA'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 3B: Humanities
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('AMS', '10', 'Stories that Make America', 3, (SELECT id FROM public.departments WHERE code = 'AMS')),
  ('CHIN', '1A', 'Elementary Chinese', 4, (SELECT id FROM public.departments WHERE code = 'CHIN')),
  ('CHIN', '1B', 'Elementary Chinese', 4, (SELECT id FROM public.departments WHERE code = 'CHIN')),
  ('CHIN', '25A', 'Intermediate Chinese', 4, (SELECT id FROM public.departments WHERE code = 'CHIN')),
  ('CHIN', '25B', 'Intermediate Chinese', 4, (SELECT id FROM public.departments WHERE code = 'CHIN')),
  ('ENGL', '1B', 'Argument and Analysis', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '10', 'Great Works of Literature', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '20', 'Introduction to Comics', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '21', 'Mystery and Detective Fiction', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '22', 'Fantasy and Science Fiction', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '30', 'Literature and the Environment', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '40', 'Contemporary World Fiction', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('ENGL', '78', 'Introduction to Shakespeare''s Drama', 3, (SELECT id FROM public.departments WHERE code = 'ENGL')),
  ('FREN', '1A', 'Elementary French', 4, (SELECT id FROM public.departments WHERE code = 'FREN')),
  ('FREN', '1B', 'Elementary French', 4, (SELECT id FROM public.departments WHERE code = 'FREN')),
  ('FREN', '25A', 'Intermediate French: Reading', 4, (SELECT id FROM public.departments WHERE code = 'FREN')),
  ('FREN', '25B', 'Intermediate French: Writing', 4, (SELECT id FROM public.departments WHERE code = 'FREN')),
  ('GERM', '1A', 'Elementary German', 4, (SELECT id FROM public.departments WHERE code = 'GERM')),
  ('GERM', '1B', 'Elementary German', 4, (SELECT id FROM public.departments WHERE code = 'GERM')),
  ('GERM', '25A', 'Intermediate German', 4, (SELECT id FROM public.departments WHERE code = 'GERM')),
  ('GERM', '25B', 'Intermediate German', 4, (SELECT id FROM public.departments WHERE code = 'GERM')),
  ('HEBR', '1A', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'HEBR')),
  ('HEBR', '1B', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'HEBR')),
  ('HUM', '21', 'Honors Reading Difference across Global Cultures', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('HUM', '90', 'Bible History and Literature', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('ITAL', '1A', 'Elementary Italian', 4, (SELECT id FROM public.departments WHERE code = 'ITAL')),
  ('ITAL', '1B', 'Elementary Italian', 4, (SELECT id FROM public.departments WHERE code = 'ITAL')),
  ('JPN', '1A', 'Elementary Japanese', 4, (SELECT id FROM public.departments WHERE code = 'JPN')),
  ('JPN', '1B', 'Elementary Japanese', 4, (SELECT id FROM public.departments WHERE code = 'JPN')),
  ('JPN', '25A', 'Intermediate Japanese', 4, (SELECT id FROM public.departments WHERE code = 'JPN')),
  ('JPN', '25B', 'Intermediate Japanese', 4, (SELECT id FROM public.departments WHERE code = 'JPN')),
  ('JWSS', '1A', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'JWSS')),
  ('JWSS', '1B', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'JWSS')),
  ('JWSS', '90', 'Bible History and Literature', 3, (SELECT id FROM public.departments WHERE code = 'JWSS')),
  ('LSTP', '10', 'Chronicles of Education', 3, (SELECT id FROM public.departments WHERE code = 'LSTP')),
  ('MDES', '90', 'Bible History and Literature', 3, (SELECT id FROM public.departments WHERE code = 'MDES')),
  ('MUSC', '12', 'Medieval and Renaissance Music', 3, (SELECT id FROM public.departments WHERE code = 'MUSC')),
  ('PHIL', '10', 'Introduction to Philosophy', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('PHIL', '61', 'Moral Issues', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('PHIL', '70A', 'Ancient Philosophy', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('PHIL', '70B', 'Early Modern Philosophy', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('PHIL', '70E', 'Medieval and Renaissance Philosophy', 3, (SELECT id FROM public.departments WHERE code = 'PHIL')),
  ('POLS', '3', 'Introduction to Political Thought', 3, (SELECT id FROM public.departments WHERE code = 'POLS')),
  ('POLS', '16', 'Power and Ideas in American Politics', 3, (SELECT id FROM public.departments WHERE code = 'POLS')),
  ('PORT', '1A', 'Elementary Portuguese I', 4, (SELECT id FROM public.departments WHERE code = 'PORT')),
  ('PORT', '1B', 'Elementary Portuguese II', 4, (SELECT id FROM public.departments WHERE code = 'PORT')),
  ('RELS', '1A', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'RELS')),
  ('RELS', '1B', 'Elementary Hebrew', 4, (SELECT id FROM public.departments WHERE code = 'RELS')),
  ('RELS', '70', 'Religious Worlds: Navigating Diversity', 3, (SELECT id FROM public.departments WHERE code = 'RELS')),
  ('RELS', '90', 'Bible History and Literature', 3, (SELECT id FROM public.departments WHERE code = 'RELS')),
  ('RUSS', '1A', 'Elementary Russian I', 4, (SELECT id FROM public.departments WHERE code = 'RUSS')),
  ('RUSS', '1B', 'Elementary Russian II', 4, (SELECT id FROM public.departments WHERE code = 'RUSS')),
  ('SPAN', '1A', 'Elementary Spanish', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('SPAN', '1B', 'Elementary Spanish', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('SPAN', '20A', 'Spanish for Heritage Speakers I', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('SPAN', '20B', 'Spanish for Heritage Speakers II', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('SPAN', '25A', 'Intermediate Spanish', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('SPAN', '25B', 'Intermediate Spanish', 4, (SELECT id FROM public.departments WHERE code = 'SPAN')),
  ('TA', '13', 'Great Comedies for Theatre', 3, (SELECT id FROM public.departments WHERE code = 'TA')),
  ('TAG', '1A', 'Elementary Tagalog I', 4, (SELECT id FROM public.departments WHERE code = 'TAG')),
  ('TAG', '1B', 'Elementary Tagalog II', 4, (SELECT id FROM public.departments WHERE code = 'TAG')),
  ('VIET', '1A', 'Elementary Vietnamese', 4, (SELECT id FROM public.departments WHERE code = 'VIET')),
  ('VIET', '1B', 'Elementary Vietnamese', 4, (SELECT id FROM public.departments WHERE code = 'VIET'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 4: Social and Behavioral Sciences
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('AAS', '33A', 'Asian Americans in U.S. History I', 3, (SELECT id FROM public.departments WHERE code = 'AAS')),
  ('AAS', '33B', 'Asian Americans in U.S. History II', 3, (SELECT id FROM public.departments WHERE code = 'AAS')),
  ('AFAM', '2A', 'African Americans and the Development of America''s History and Government', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AFAM', '2B', 'African Americans and the Development of America''s History and Government', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AMS', '11', 'Visions of Democracy', 3, (SELECT id FROM public.departments WHERE code = 'AMS')),
  ('ANTH', '11', 'Cultural Anthropology', 3, (SELECT id FROM public.departments WHERE code = 'ANTH')),
  ('CCS', '10A', 'Mexican Americans and the Development of U.S. History and Government', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('CCS', '10B', 'Mexican Americans and the Development of U.S. History and Government', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('CHAD', '70', 'Lifespan Development in a Global Context', 3, (SELECT id FROM public.departments WHERE code = 'CHAD')),
  ('CHAD', '75', 'Imagination, Play and Adult Creativity', 3, (SELECT id FROM public.departments WHERE code = 'CHAD')),
  ('CHAD', '76', 'Child Development Among Media and Emerging Technologies', 3, (SELECT id FROM public.departments WHERE code = 'CHAD')),
  ('COMM', '10', 'Communication and Human Relationships', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('COMM', '21', 'Performing Culture and Society', 3, (SELECT id FROM public.departments WHERE code = 'COMM')),
  ('CS', '25', 'The Digital World and Society', 3, (SELECT id FROM public.departments WHERE code = 'CS')),
  ('ECON', '1B', 'Principles of Economics: Microeconomics', 3, (SELECT id FROM public.departments WHERE code = 'ECON')),
  ('ENGR', '25', 'The Digital World and Society', 3, (SELECT id FROM public.departments WHERE code = 'ENGR')),
  ('GEOG', '10', 'Cultural Geography', 3, (SELECT id FROM public.departments WHERE code = 'GEOG')),
  ('GEOG', '12', 'World Regional Geography', 3, (SELECT id FROM public.departments WHERE code = 'GEOG')),
  ('GERO', '99', 'Death, Dying and Religions', 3, (SELECT id FROM public.departments WHERE code = 'GERO')),
  ('HIST', '1A', 'World History to 1500', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HIST', '1B', 'World History from 1500', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HIST', '10A', 'Western Civilization', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HIST', '10B', 'Western Civilization', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HIST', '15', 'Essentials of U.S. History', 3, (SELECT id FROM public.departments WHERE code = 'HIST')),
  ('HUM', '99', 'Death, Dying and Religions', 3, (SELECT id FROM public.departments WHERE code = 'HUM')),
  ('JOUR', '50', 'Navigating the News', 3, (SELECT id FROM public.departments WHERE code = 'JOUR')),
  ('JS', '25', 'Introduction to Human Rights and Justice', 3, (SELECT id FROM public.departments WHERE code = 'JS')),
  ('LING', '20', 'Nature of Language', 3, (SELECT id FROM public.departments WHERE code = 'LING')),
  ('LING', '25', 'Languages of the World', 3, (SELECT id FROM public.departments WHERE code = 'LING')),
  ('PH', '15', 'Human Life Span', 3, (SELECT id FROM public.departments WHERE code = 'PH')),
  ('PH', '21', 'Public Health Through Film', 3, (SELECT id FROM public.departments WHERE code = 'PH')),
  ('PH', '99', 'Introduction to Public Health', 3, (SELECT id FROM public.departments WHERE code = 'PH')),
  ('POLS', '2', 'Introduction to Comparative Politics', 3, (SELECT id FROM public.departments WHERE code = 'POLS')),
  ('POLS', '4', 'Introduction to International Relations', 3, (SELECT id FROM public.departments WHERE code = 'POLS')),
  ('POLS', '15', 'Essentials of U.S. & California Government', 3, (SELECT id FROM public.departments WHERE code = 'POLS')),
  ('PSYC', '1', 'Introduction to Psychology', 3, (SELECT id FROM public.departments WHERE code = 'PSYC')),
  ('RELS', '99', 'Death, Dying and Religions', 3, (SELECT id FROM public.departments WHERE code = 'RELS')),
  ('SOCI', '1', 'Introduction to Sociology', 3, (SELECT id FROM public.departments WHERE code = 'SOCI')),
  ('SOCI', '80', 'Social Problems', 3, (SELECT id FROM public.departments WHERE code = 'SOCI')),
  ('WGSS', '10', 'Women, Gender, and Sexuality Studies', 3, (SELECT id FROM public.departments WHERE code = 'WGSS')),
  ('WGSS', '16A', 'Women of Color in United States History I', 3, (SELECT id FROM public.departments WHERE code = 'WGSS')),
  ('WGSS', '16B', 'Women of Color in U.S. History II', 3, (SELECT id FROM public.departments WHERE code = 'WGSS')),
  ('WGSS', '20', 'Women of Color in the U.S.', 3, (SELECT id FROM public.departments WHERE code = 'WGSS'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 5A: Physical Science
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('ASTR', '10', 'Descriptive Astronomy', 3, (SELECT id FROM public.departments WHERE code = 'ASTR')),
  ('CHE', '1', 'Design of Coffee', 4, (SELECT id FROM public.departments WHERE code = 'CHE')),
  ('CHEM', '1A', 'General Chemistry', 5, (SELECT id FROM public.departments WHERE code = 'CHEM')),
  ('CHEM', '1B', 'General Chemistry', 5, (SELECT id FROM public.departments WHERE code = 'CHEM')),
  ('CHEM', '30A', 'Introductory Chemistry', 4, (SELECT id FROM public.departments WHERE code = 'CHEM')),
  ('ENGR', '5', 'Science of High Technology', 3, (SELECT id FROM public.departments WHERE code = 'ENGR')),
  ('GEOG', '1', 'Physical Geography', 3, (SELECT id FROM public.departments WHERE code = 'GEOG')),
  ('GEOL', '1', 'General Geology', 4, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '3', 'Planet Earth', 3, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '5', 'Earth Science for Sustainability', 3, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '6', 'Geology of California', 3, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '7', 'Earth, Time and Life', 4, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '9', 'Earth Disasters', 4, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('METR', '10', 'Weather and Climate', 3, (SELECT id FROM public.departments WHERE code = 'METR')),
  ('METR', '12', 'Global Warming: Science and Solutions', 3, (SELECT id FROM public.departments WHERE code = 'METR')),
  ('NUFS', '1A', 'Physical Science of Food', 3, (SELECT id FROM public.departments WHERE code = 'NUFS')),
  ('PHYS', '1', 'Elementary Physics', 3, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '2A', 'Fundamentals of Physics', 4, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '2B', 'Fundamentals of Physics', 4, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '23', 'Animation Physics', 3, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '50', 'General Physics I: Mechanics', 4, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '51', 'General Physics II: Electricity and Magnetism', 4, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('PHYS', '52', 'General Physics III: Waves, Light, Heat', 4, (SELECT id FROM public.departments WHERE code = 'PHYS')),
  ('SCED', '5', 'Earth Science for Sustainability', 3, (SELECT id FROM public.departments WHERE code = 'SCED'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 5B: Life Science
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('ANTH', '12', 'Introduction to Human Evolution', 3, (SELECT id FROM public.departments WHERE code = 'ANTH')),
  ('BIOL', '10', 'The Living World', 3, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '20', 'Ecological Biology', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '21', 'Human Biology', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '30', 'Principles of Biology I', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '31', 'Principles of Biology II', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '65', 'Human Anatomy', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '65O', 'Human Anatomy', 4, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('BIOL', '66', 'Human Physiology', 5, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('ENVS', '10', 'Life on a Changing Planet', 3, (SELECT id FROM public.departments WHERE code = 'ENVS')),
  ('GEOL', '8', 'The Age of the Dinosaurs', 3, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GLST', '1B', 'Introduction to Global Studies', 3, (SELECT id FROM public.departments WHERE code = 'GLST')),
  ('MICR', '20', 'General Bacteriology', 5, (SELECT id FROM public.departments WHERE code = 'MICR')),
  ('NUFS', '16', 'Science, Physiology, and Nutrition', 3, (SELECT id FROM public.departments WHERE code = 'NUFS')),
  ('PH', '52', 'Public Health Biology', 3, (SELECT id FROM public.departments WHERE code = 'PH'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 5C: Lab Courses
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('ASTR', '11L', 'Introductory Astronomy Lab', 1, (SELECT id FROM public.departments WHERE code = 'ASTR')),
  ('BIOL', '150', 'Field Studies in Natural History', 1, (SELECT id FROM public.departments WHERE code = 'BIOL')),
  ('CHEM', '5', 'Dinner Party Chemistry', 1, (SELECT id FROM public.departments WHERE code = 'CHEM')),
  ('GEOL', '4L', 'Earth Systems Lab', 1, (SELECT id FROM public.departments WHERE code = 'GEOL')),
  ('GEOL', '150', 'Field Studies in Natural History', 1, (SELECT id FROM public.departments WHERE code = 'GEOL'))
ON CONFLICT (course_code, course_number) DO NOTHING;

-- Area 6: Ethnic Studies
INSERT INTO public.courses (course_code, course_number, title, units, department_id) VALUES
  ('AAS', '1', 'Introduction to Asian American Studies', 3, (SELECT id FROM public.departments WHERE code = 'AAS')),
  ('AAS', '25', 'The Changing Majority: Power and Ethnicity in America', 3, (SELECT id FROM public.departments WHERE code = 'AAS')),
  ('AAS', '159', 'Asian American Media Representation and Popular Culture', 3, (SELECT id FROM public.departments WHERE code = 'AAS')),
  ('AFAM', '22', 'The Humanities in African American Culture', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AFAM', '25', 'The Changing Majority: Power and Ethnicity in America', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AFAM', '134', 'The Black Civil Rights Movements', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AFAM', '158', 'Race, Sport, Activism & Social Movements', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('AFAM', '162', 'The Aesthetics of Hip-Hop', 3, (SELECT id FROM public.departments WHERE code = 'AFAM')),
  ('CCS', '1', 'Introduction to Chicana and Chicano Studies', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('CCS', '25', 'The Changing Majority: Power and Ethnicity in America', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('CCS', '30', 'Race and Ethnicity in Public Space', 3, (SELECT id FROM public.departments WHERE code = 'CCS')),
  ('NAIS', '1', 'Intro to Native American and Indigenous Studies', 3, (SELECT id FROM public.departments WHERE code = 'NAIS')),
  ('NAIS', '2', 'California Indigenous Peoples', 3, (SELECT id FROM public.departments WHERE code = 'NAIS'))
ON CONFLICT (course_code, course_number) DO NOTHING;
